# Generated by Django 5.1.7 on 2025-03-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profiles",
            new_name="Profile",
        ),
    ]
