# Generated by Django 5.1.7 on 2025-08-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
