# Generated by Django 5.1.7 on 2025-08-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=False),
        ),
    ]
