# Generated by Django 5.1.7 on 2025-03-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="post/post-images.png", upload_to="imgage/post"
            ),
        ),
    ]
