# Generated by Django 5.1.7 on 2025-03-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.BooleanField(default=False),
        ),
    ]
