# Generated by Django 5.1.7 on 2025-03-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0003_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                default="profile/profile.png", upload_to="profile/user"
            ),
        ),
    ]
