# Generated by Django 5.1.7 on 2025-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0004_alter_comment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                default="profile/profile.jpeg", upload_to="profile/user"
            ),
        ),
    ]
