# Generated by Django 5.1.7 on 2025-03-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0008_comment_parent_replay_delete_replaycomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="image",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="updated_date",
        ),
        migrations.DeleteModel(
            name="Replay",
        ),
    ]
