# Generated by Django 5.1.7 on 2025-03-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0009_remove_comment_email_remove_comment_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="message",
            new_name="content",
        ),
    ]
