# Generated by Django 5.1.7 on 2025-03-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0011_remove_comment_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
